<?php

namespace Database\Seeders;

use App\Models\Slug;
use Illuminate\Database\Seeder;

class SlugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $slugs = [
            ['id' => '1', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '1', 'name' => 'priem-czvetnogo-metalla', 'content_id' => '1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '2', 'name' => 'priem-loma-kabelya', 'content_id' => '2', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '3', 'name' => 'priem-akkumulyatorov', 'content_id' => '3', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '4', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '4', 'name' => 'priem-chernogo-loma', 'content_id' => '4', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '5', 'name' => 'priem-transformatorov', 'content_id' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '6', 'name' => 'priem-elektrodvigatelej', 'content_id' => '6', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7', 'slugable_type' => 'App\\Models\\Market', 'slugable_id' => '7', 'name' => 'redkozemelnyij-metall', 'content_id' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '1', 'name' => 'priem-medi', 'content_id' => '8', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '2', 'name' => 'priem-alyuminiya', 'content_id' => '9', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '10', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '3', 'name' => 'priem-bronzyi', 'content_id' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '11', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '4', 'name' => 'priem-svincza', 'content_id' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '12', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '5', 'name' => 'priem-latuni', 'content_id' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '13', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '6', 'name' => 'priem-nerzhavejki', 'content_id' => '13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '14', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '7', 'name' => 'priem-stali', 'content_id' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '15', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '8', 'name' => 'priem-lom-chuguna', 'content_id' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '16', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '9', 'name' => 'priem-lom-oczinkovki', 'content_id' => '16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '17', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '10', 'name' => 'priem-chermeta', 'content_id' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '18', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '11', 'name' => 'priem-titana', 'content_id' => '18', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '19', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '12', 'name' => 'priem-volframa', 'content_id' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '20', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '13', 'name' => 'priem-lom-melxiora', 'content_id' => '20', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '21', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '14', 'name' => 'priem-babbita', 'content_id' => '21', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '22', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '15', 'name' => 'priem-molibdena', 'content_id' => '22', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '23', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '16', 'name' => 'priem-lom-nikelya', 'content_id' => '23', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '24', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '17', 'name' => 'priem-lom-czinka', 'content_id' => '24', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '25', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '18', 'name' => 'priem-silumina', 'content_id' => '25', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '26', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '19', 'name' => 'priem-lom-pripoya', 'content_id' => '26', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '27', 'slugable_type' => 'App\\Models\\Category', 'slugable_id' => '20', 'name' => 'priem-lom-olova', 'content_id' => '27', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '28', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '1', 'name' => 'priem-medi-blesk', 'content_id' => '28', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '29', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '2', 'name' => 'priem-medi-v-silovom-kabele', 'content_id' => '29', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '30', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '3', 'name' => 'priem-kuskovoj-medi', 'content_id' => '30', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '31', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '4', 'name' => 'priem-medi-otborka', 'content_id' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '32', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '5', 'name' => 'priem-obozhzhenoj-mezhi', 'content_id' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '33', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '6', 'name' => 'priem-medi-v-masle', 'content_id' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '34', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '7', 'name' => 'priem-elektrotexnicheskoj-medi-v-masle', 'content_id' => '34', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '35', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '8', 'name' => 'priem-mednoj-katanki', 'content_id' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '36', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '9', 'name' => 'shinka-transformatornaya-mednaya', 'content_id' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '37', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '10', 'name' => 'priem-loma-emalprovoda', 'content_id' => '37', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '38', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '11', 'name' => 'priem-miks-medi-nesortovaya-med', 'content_id' => '38', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '39', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '12', 'name' => 'priem-medi-v-steklotkani', 'content_id' => '39', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '40', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '13', 'name' => 'priem-luzhenoj-medi', 'content_id' => '40', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '41', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '14', 'name' => 'priem-mednoj-struzhki-sechki', 'content_id' => '41', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '42', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '15', 'name' => 'priem-mednoj-provoloki', 'content_id' => '42', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '43', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '16', 'name' => 'radiatoryi-mednyie', 'content_id' => '43', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '44', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '17', 'name' => 'priem-medno-alyuminievyix-radiatorov', 'content_id' => '44', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '45', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '18', 'name' => 'priem-alyuminievo-mednyix-radiatorov', 'content_id' => '45', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '46', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '19', 'name' => 'priem-elektrotexnicheskogo-alyuminiya', 'content_id' => '46', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '47', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '20', 'name' => 'priem-provoda-as', 'content_id' => '47', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '48', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '21', 'name' => 'priem-alyuminiya-v-silovom-kabele', 'content_id' => '48', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '49', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '22', 'name' => 'priem-pishhevogo-alyuminiya', 'content_id' => '49', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '50', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '23', 'name' => 'priem-alyuminievogo-profilya-ad-31', 'content_id' => '50', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '51', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '24', 'name' => 'alyuminievyie-ershi-trubyi', 'content_id' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '52', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '25', 'name' => 'alyuminievyie-diski', 'content_id' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '53', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '26', 'name' => 'priem-ofseta', 'content_id' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '54', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '27', 'name' => 'priem-motornogo-alyuminiya', 'content_id' => '54', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '55', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '28', 'name' => 'priem-splava-alyuminiya-amg', 'content_id' => '55', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '56', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '29', 'name' => 'priem-miks-alyuminiya', 'content_id' => '56', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '57', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '30', 'name' => 'priem-avtomobilnyix-nomerov', 'content_id' => '57', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '58', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '31', 'name' => 'priem-splava-alyuminiya-amcz', 'content_id' => '58', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '59', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '32', 'name' => 'priem-alyuminievyix-banok', 'content_id' => '59', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '60', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '33', 'name' => 'priem-alyuminievoj-struzhki', 'content_id' => '60', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '61', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '34', 'name' => 'alyuminievaya-folga', 'content_id' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '62', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '35', 'name' => 'priem-alyuminievyix-radiatorov', 'content_id' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '63', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '36', 'name' => 'priem-alyuminievoj-provoloki', 'content_id' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '64', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '37', 'name' => 'priem-marochnoj-bronzyi-brazh-brof-brocz', 'content_id' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '65', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '38', 'name' => 'miks-bronzyi-nesortovoj-lom', 'content_id' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '66', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '39', 'name' => 'priem-kuskovoj-bronzyi', 'content_id' => '66', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '67', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '40', 'name' => 'priem-bronzovyix-izdelij', 'content_id' => '67', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '68', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '41', 'name' => 'priem-bronzovoj-struzhki', 'content_id' => '68', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '69', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '42', 'name' => 'priem-svincza-v-chushkax', 'content_id' => '69', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '70', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '43', 'name' => 'priem-svincza-v-silovom-kabele', 'content_id' => '70', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '71', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '44', 'name' => 'priem-kabelya-so-svinczovoj-obolochkoj', 'content_id' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '72', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '45', 'name' => 'priem-kabelnogo-svincza-ochishhennogo', 'content_id' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '73', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '46', 'name' => 'kuskovoj-svinecz-kusok-bolee-10-mm', 'content_id' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '74', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '47', 'name' => 'priem-svinczovyix-plastin', 'content_id' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '75', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '48', 'name' => 'kabelnyij-svinecz-ne-ochishhennyij-ot-gudrona', 'content_id' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '76', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '49', 'name' => 'priem-svincza-pereplav', 'content_id' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '77', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '50', 'name' => 'priem-svincza-v-telefonnom-kabele', 'content_id' => '77', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '78', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '51', 'name' => 'priem-shinomontazhnyix-gruzikov', 'content_id' => '78', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '79', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '52', 'name' => 'priem-svinczovoj-provoloki', 'content_id' => '79', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '80', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '53', 'name' => 'priem-marochnoj-latuni-l-63', 'content_id' => '80', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '81', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '54', 'name' => 'priem-marochnoj-latuni-l-90', 'content_id' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '82', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '55', 'name' => 'priem-latuni-ls-59', 'content_id' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '83', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '56', 'name' => 'priem-miks-latuni', 'content_id' => '83', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '84', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '57', 'name' => 'priem-kuskovoj-latuni', 'content_id' => '84', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '85', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '58', 'name' => 'priem-latunnyix-radiatorov', 'content_id' => '85', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '86', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '59', 'name' => 'priem-latunnoj-struzhki', 'content_id' => '86', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '87', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '60', 'name' => 'priem-vyisokolegirovannoj-stali-15-99-ni', 'content_id' => '87', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '88', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '61', 'name' => 'priem-nerzhavejka-10-gabarit', 'content_id' => '88', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '89', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '62', 'name' => 'priem-nerzhavejki-10-ne-gabarit', 'content_id' => '89', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '90', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '63', 'name' => 'priem-nerzhavejki-8-gabarit', 'content_id' => '90', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '91', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '64', 'name' => 'priem-nerzhavejki-8-ne-gabarit', 'content_id' => '91', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '92', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '65', 'name' => 'priem-struzhki-nerzhavejki', 'content_id' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '93', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '66', 'name' => 'lom-stali-nizkolegirovannoj-1-6-ni', 'content_id' => '93', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '94', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '67', 'name' => 'priem-stali-5a', 'content_id' => '94', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '95', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '68', 'name' => 'priem-stali-3a-3a1', 'content_id' => '95', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '96', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '69', 'name' => 'priem-stalnoj-provoloki', 'content_id' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '97', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '70', 'name' => 'stalnaya-struzhka-16-a', 'content_id' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '98', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '71', 'name' => 'gabaritnyij-chugun-17a', 'content_id' => '98', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '99', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '72', 'name' => 'lom-negabaritnogo-chuguna-20a', 'content_id' => '99', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '100', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '73', 'name' => 'priem-chernogo-metalla-22a', 'content_id' => '100', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '101', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '74', 'name' => '12a-zhest-oczinkovka', 'content_id' => '101', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '102', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '75', 'name' => 'priem-loma-gabaritnogo-3arm', 'content_id' => '102', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '103', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '76', 'name' => 'priem-loma-negabaritnogo-5arm', 'content_id' => '103', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '104', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '77', 'name' => 'lom-13a-stalnyie-kanatyi-provoloka-armatura', 'content_id' => '104', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '105', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '78', 'name' => 'priem-chernogo-metalla-4a', 'content_id' => '105', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '106', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '79', 'name' => 'priem-tonkostennogo-metalloloma-12a1', 'content_id' => '106', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '107', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '80', 'name' => 'priem-struzhki-chernogo-metalloloma', 'content_id' => '107', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '108', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '81', 'name' => 'priem-armaturyi', 'content_id' => '108', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '109', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '82', 'name' => 'priem-zhesti', 'content_id' => '109', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '110', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '83', 'name' => 'priem-titana-vt1-0', 'content_id' => '110', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '111', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '84', 'name' => 'priem-nesortovogo-titana-miks', 'content_id' => '111', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '112', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '85', 'name' => 'struzhka-titana', 'content_id' => '112', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '113', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '86', 'name' => 'volfram-provoloka', 'content_id' => '113', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '114', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '87', 'name' => 'lom-volframovyix-elektrodov', 'content_id' => '114', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '115', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '88', 'name' => 'priem-melxiora-mn-19', 'content_id' => '115', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '116', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '89', 'name' => 'priem-melxiora-mn–40', 'content_id' => '116', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '117', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '90', 'name' => 'priem-splava-mncz-15-20', 'content_id' => '117', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '118', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '91', 'name' => 'priem-babbita-b-83', 'content_id' => '118', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '119', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '92', 'name' => 'priem-babbita-samoplav', 'content_id' => '119', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '120', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '93', 'name' => 'priem-babbita-b-16', 'content_id' => '120', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '121', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '94', 'name' => 'lom-molibdena-pechnogo', 'content_id' => '121', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '122', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '95', 'name' => 'prokat-iz-molibdena', 'content_id' => '122', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '123', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '96', 'name' => 'priem-loma-vk-tk', 'content_id' => '123', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '124', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '97', 'name' => 'priem-mednogo-kabelya', 'content_id' => '124', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '125', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '98', 'name' => 'priem-silovogo-kabelya', 'content_id' => '125', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '126', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '99', 'name' => 'priem-telefonnogo-kabelya', 'content_id' => '126', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '127', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '100', 'name' => 'priem-kompyuternogo-kabelya', 'content_id' => '127', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '128', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '101', 'name' => 'priem-alyuminievogo-kabelya', 'content_id' => '128', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '129', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '102', 'name' => 'svinczovyij-kabel', 'content_id' => '129', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '130', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '103', 'name' => 'priem-montazhnogo-kabelya', 'content_id' => '130', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '131', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '104', 'name' => 'priem-obmotochnogo-kabelya', 'content_id' => '131', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '132', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '105', 'name' => 'priem-slityix-akkumulyatorov', 'content_id' => '132', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '133', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '106', 'name' => 'priem-gelevyix-akkumulyatorov', 'content_id' => '133', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '134', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '107', 'name' => 'priem-avtomobilnyix-akkumulyatorov', 'content_id' => '134', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '135', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '108', 'name' => 'priem-svinczovyix-akkumulyatorov', 'content_id' => '135', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '136', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '109', 'name' => 'priem-tyagovyix-akkumulyatorov', 'content_id' => '136', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '137', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '110', 'name' => 'priem-akkumulyatorov-ot-ibp', 'content_id' => '137', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '138', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '111', 'name' => 'priem-ebonitovyix-akkumulyatorov', 'content_id' => '138', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '139', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '112', 'name' => 'priem-shhelochnyix-akkumulyatorov', 'content_id' => '139', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '140', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '113', 'name' => 'priem-transformatorov-s-mednoj-shinoj', 'content_id' => '140', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '141', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '114', 'name' => 'priem-transformatorov-s-alyuminievoj-shinoj', 'content_id' => '141', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '142', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '115', 'name' => 'priem-loma-elektrogeneratoryi', 'content_id' => '142', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '143', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '116', 'name' => 'priem-loma-starterov', 'content_id' => '143', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '144', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '117', 'name' => 'priem-loma-kompressoryi', 'content_id' => '144', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '145', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '118', 'name' => 'priem-lom-nikelya', 'content_id' => '145', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '146', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '119', 'name' => 'priem-silumina', 'content_id' => '146', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '147', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '120', 'name' => 'priem-lom-pripoya', 'content_id' => '147', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '148', 'slugable_type' => 'App\\Models\\Product', 'slugable_id' => '121', 'name' => 'priem-lom-olova', 'content_id' => '148', 'created_at' => now(), 'updated_at' => now()],
        ];

        Slug::insert($slugs);
    }
}
