<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\Auth;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param Throwable $e
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response|\Symfony\Component\HttpFoundation\Response
     * @throws Throwable
     */
    public function render($request, Throwable $e)
    {
        if($request->segment(1) === "administrator-panel")
        {
            if ($this->isHttpException($e)) {

                if ($e->getStatusCode() == 404) {
                    return response()->view('admin.errors.' . '404', [], 404);
                }

            }
        }
        else
        {
            if ($this->isHttpException($e)) {

                if ($e->getStatusCode() == 404) {
                    return response()->view('errors.' . '404', [], 404);
                }

            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
